version: '3.1'

services:
  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ".env.prod"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    depends_on:
      - db
    env_file:
      - ".env.prod"
  schedule:
    container_name: schedule
    build:
      context: .
    command: python schedule.py
    depends_on:
      - db
      - tgbot
    env_file:
      - ".env.prod"
volumes:
  postgres_data: