version: '3.1'

services:
  tgbot:
    container_name: bot
    command: python app.py
    build:
      context: .
    restart: always
    depends_on:
      - db
    env_file:
      - ".env.prod"
  db:
    container_name: database
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ".env.prod"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: